name: django-app
services:
- name: web
  source_dir: /
  github:
    repo: arbak/django-do
    branch: main
  run_command: ./start.sh
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  envs:
  - key: DJANGO_SETTINGS_MODULE
    value: myproject.settings
  - key: SECRET_KEY
    value: django-insecure-change-this-in-production-12345
  - key: DEBUG
    value: "False"
  - key: ALLOWED_HOSTS
    value: "*.ondigitalocean.app"
  - key: DJANGO_SUPERUSER_USERNAME
    value: "admin"
  - key: DJANGO_SUPERUSER_EMAIL
    value: "admin@example.com"
  - key: DJANGO_SUPERUSER_PASSWORD
    value: "admin123"
  routes:
  - path: /
  health_check:
    http_path: /
    initial_delay_seconds: 10
    period_seconds: 10
    timeout_seconds: 5
    success_threshold: 1
    failure_threshold: 3
